### ISSUE TITLE
Alt+V shortcut typo

### ISSUE THREAD

**Issue by jmicu** [matt92martin/decipher-chrome-extensions#6]
alt+v URL has an extraneous forward slash immediately preceding "selfserve" which causes the XML list page to load, but without any files listed. example: 

currently [https://v2.decipherinc.com/admin/vc/list?file=/selfserve/20fb/hpt17036/survey.xml](https://v2.decipherinc.com/admin/vc/list?file=/selfserve/20fb/hpt17036/survey.xml)
needs to be [https://v2.decipherinc.com/admin/vc/list?file=selfserve/20fb/hpt17036/survey.xml](https://v2.decipherinc.com/admin/vc/list?file=selfserve/20fb/hpt17036/survey.xml)

**Comment by simplecodemerchant** [comment]
This is fixed in 2.0.3

**Comment by simplecodemerchant** [comment]
Had this happen again. Reopened
